<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGbLxPL0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGbLxPL0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGbLxPL0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGbLxPL0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGbLxPL0\App_KernelDevDebugContainer([
    'container.build_hash' => 'GbLxPL0',
    'container.build_id' => '963b9ff1',
    'container.build_time' => 1677675079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGbLxPL0');
