<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_adresses' => [[], ['_controller' => 'App\\Controller\\AdressesController::getAdresseList'], [], [['text', '/api/adresses']], [], [], []],
    'app_detailAdresses' => [['id'], ['_controller' => 'App\\Controller\\AdressesController::getDetailAdresse'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/adresses']], [], [], []],
    'app_detailName' => [['nom'], ['_controller' => 'App\\Controller\\AdressesController::getDetailName'], [], [['variable', '/', '[^/]++', 'nom', true], ['text', '/api/adresses/nom']], [], [], []],
];
