<?php

namespace ContainerClGwD3w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O4kuXe5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o4kuXe5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o4kuXe5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdressesController::getAdresseList' => ['privates', '.service_locator.5D28ebW', 'get_ServiceLocator_5D28ebWService', true],
            'App\\Controller\\AdressesController::getDetailAdresse' => ['privates', '.service_locator.z7wYYTK', 'get_ServiceLocator_Z7wYYTKService', true],
            'App\\Controller\\AdressesController::getDetailName' => ['privates', '.service_locator.5D28ebW', 'get_ServiceLocator_5D28ebWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdressesController:getAdresseList' => ['privates', '.service_locator.5D28ebW', 'get_ServiceLocator_5D28ebWService', true],
            'App\\Controller\\AdressesController:getDetailAdresse' => ['privates', '.service_locator.z7wYYTK', 'get_ServiceLocator_Z7wYYTKService', true],
            'App\\Controller\\AdressesController:getDetailName' => ['privates', '.service_locator.5D28ebW', 'get_ServiceLocator_5D28ebWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdressesController::getAdresseList' => '?',
            'App\\Controller\\AdressesController::getDetailAdresse' => '?',
            'App\\Controller\\AdressesController::getDetailName' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdressesController:getAdresseList' => '?',
            'App\\Controller\\AdressesController:getDetailAdresse' => '?',
            'App\\Controller\\AdressesController:getDetailName' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
