<?php

namespace ContainerClGwD3w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z7wYYTKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z7wYYTK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z7wYYTK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adresse' => ['privates', '.errored..service_locator.z7wYYTK.App\\Entity\\Adresse', NULL, 'Cannot autowire service ".service_locator.z7wYYTK": it needs an instance of "App\\Entity\\Adresse" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'adresse' => 'App\\Entity\\Adresse',
            'serializer' => '?',
        ]);
    }
}
